set-option -g default-shell /bin/zsh 
set -ga terminal-overrides ',xterm-256color:Tc'
set-option -g mouse on

source-file ~/.config/tmux/restore_sessions.conf
source-file ~/.config/tmux/pomodoro.conf
source-file ~/.config/tmux/status_bar.conf
source-file ~/.config/tmux/terminal.conf
source-file ~/.config/tmux/allow_passthrough.conf
source-file ~/.config/tmux/yank.conf
source-file ~/.config/tmux/_other.conf

set -g @plugin 'tmux-plugins/tmux-yank'

run '~/.tmux/plugins/tpm/tpm'
