# forwarding some modified key combinations cleanly, 
# especially keys like Shift+Enter, Ctrl+Enter, Alt+Enter
set -g extended-keys on


# this format work better with pi
set -g extended-keys-format csi-u

# remove this unused bind key 
# that opens a new tmux window
unbind-key -n C-Enter
