bind-key g display-popup -w 80% -h 80% -E -d "#{pane_current_path}" "lazygit"

bind-key l run-shell '~/.local/bin/tmux-toggle-last-pane.sh'

# Fuzzy finder with pane preview
bind-key f display-popup \
  -E \
  -w 90% \
  -h 85% \
  "~/.local/bin/tmux-fzf-switch.sh"
