return {
  "jay-babu/mason-nvim-dap.nvim",
  opts = {
    ensure_installed = {
      "bacon",
      "bacon-ls",
      "cmakelang",
      "cmakelint",
      "codelldb",
      "dart-debug-adapter",
      "debugpy",
      "delve",
      "docker-compose-language-service",
      "eslint-lsp",
      "gitui",
      "gofumpt",
      "goimports",
      "golangci-lint",
      "gopls",
      "hadolint",
      "helm-ls",
      "js-debug-adapter",
      "json-lsp",
      "lua-language-server",
      "markdown-toc",
      "markdownlint-cli2",
      "marksman",
      "neocmakelsp",
      -- "nil",
      "prettier",
      "pyright",
      "ruff",
      "shellcheck",
      "shfmt",
      "sqlfluff",
      "stylua",
      "svelte-language-server",
      "tailwindcss-language-server",
      "taplo",
      "terraform-ls",
      "tflint",
      "vtsls",
      "yaml-language-server",
      "zls",
    },
  },
}
