return {
  "nvim-treesitter/nvim-treesitter",
  dependencies = {},
  run = ":TSUpdate",
  opts = {
    ensure_installed = {
      "bash",
      "c",
      "cmake",
      "css",
      "dart",
      "diff",
      "dockerfile",
      "dtd",
      "git_config",
      "git_rebase",
      "gitattributes",
      "gitcommit",
      "gitignore",
      "go",
      "gomod",
      "gosum",
      "gowork",
      "hcl",
      "helm",
      "html",
      "hurl",
      "javascript",
      "jsdoc",
      "json",
      "json5",
      "lua",
      "luadoc",
      "luap",
      "markdown",
      "markdown_inline",
      "ninja",
      "nu",
      "printf",
      "python",
      "query",
      "regex",
      "ripple",
      "ron",
      "rst",
      "rust",
      "sql",
      "svelte",
      "terraform",
      "toml",
      "tsx",
      "typescript",
      "vim",
      "vimdoc",
      "xml",
      "yaml",
      "tsx",
    },
    highlight = {
      -- enable = false,
    },
  },
}
